import { FitnessBook } from "@/types";

export const booksData: FitnessBook[] = [
  // ==================== FITNESS ====================
  {
    id: "starting-strength",
    title: "Starting Strength",
    author: "Mark Rippetoe",
    category: "fitness",
    description: "Bible silového tréninku. Detailní průvodce základními cviky s činkou - dřep, bench press, mrtvý tah.",
    pages: 347,
    rating: 4.8,
    tags: ["Síla", "Činka", "Základy"],
    emoji: "🏋️",
  },
  {
    id: "bigger-leaner-stronger",
    title: "Bigger Leaner Stronger",
    author: "Michael Matthews",
    category: "fitness",
    description: "Vědecky podložený přístup k budování svalů a spalování tuků. Praktický a srozumitelný.",
    pages: 394,
    rating: 4.6,
    tags: ["Hypertrofie", "Výživa", "Program"],
    emoji: "💪",
  },
  {
    id: "atleticky-trenink",
    title: "Atletický trénink",
    author: "Pavel Tsatsouline",
    category: "fitness",
    description: "Kettlebell a síla bez objemu. Minimalistický přístup k maximální výkonnosti.",
    pages: 288,
    rating: 4.5,
    tags: ["Kettlebell", "Síla", "Minimalizmus"],
    emoji: "🔔",
  },
  {
    id: "convict-conditioning",
    title: "Convict Conditioning",
    author: "Paul Wade",
    category: "fitness",
    description: "Trénink s vlastní váhou dovedený k dokonalosti. Od nuly k jednostrannému dřepu a kliku na jedné ruce.",
    pages: 304,
    rating: 4.4,
    tags: ["Kalistenika", "Vlastní váha", "Progrese"],
    emoji: "🔗",
  },

  // ==================== MINDSET ====================
  {
    id: "atomove-navyky",
    title: "Atomové návyky",
    author: "James Clear",
    category: "mindset",
    description: "Jak vybudovat dobré návyky a zbavit se špatných. Systém malých změn s velkým dopadem.",
    pages: 320,
    rating: 4.9,
    tags: ["Návyky", "Produktivita", "Systémy"],
    emoji: "⚛️",
  },
  {
    id: "cant-hurt-me",
    title: "Nemůžeš mi ublížit",
    author: "David Goggins",
    category: "mindset",
    description: "Příběh nejtvrďáka planety. Jak překonat vlastní limity a stát se neporazitelným.",
    pages: 364,
    rating: 4.7,
    tags: ["Motivace", "Odolnost", "Limity"],
    emoji: "🔥",
  },
  {
    id: "extreme-ownership",
    title: "Extrémní vlastnictví",
    author: "Jocko Willink",
    category: "mindset",
    description: "Lekce vedení od Navy SEAL. Převezmi odpovědnost za vše ve svém životě.",
    pages: 320,
    rating: 4.6,
    tags: ["Leadership", "Disciplína", "Navy SEAL"],
    emoji: "⚓",
  },
  {
    id: "relentless",
    title: "Relentless",
    author: "Tim Grover",
    category: "mindset",
    description: "Trenér Michaela Jordana odhaluje mentalitu šampiónů. Co dělá nejlepší nejlepšími.",
    pages: 256,
    rating: 4.5,
    tags: ["Mentalita", "Šampión", "Elita"],
    emoji: "🏆",
  },

  // ==================== VÝŽIVA ====================
  {
    id: "jak-nezemrit",
    title: "Jak nezemřít",
    author: "Michael Greger",
    category: "nutrition",
    description: "Vědecky podložený průvodce výživou pro prevenci nemocí a dlouhověkost.",
    pages: 576,
    rating: 4.7,
    tags: ["Zdraví", "Prevence", "Rostlinná strava"],
    emoji: "🥦",
  },
  {
    id: "vyziva-sportovcu",
    title: "Výživa sportovců",
    author: "Asker Jeukendrup",
    category: "nutrition",
    description: "Kompletní průvodce sportovní výživou. Makra, timing, suplementace a hydratace.",
    pages: 432,
    rating: 4.5,
    tags: ["Sport", "Makra", "Suplementy"],
    emoji: "🥗",
  },
  {
    id: "metabolicky-efekt",
    title: "Metabolický efekt",
    author: "Jade Teta",
    category: "nutrition",
    description: "Jak zrychlit metabolismus a spalovat tuk efektivněji. Hormonální přístup k výživě.",
    pages: 336,
    rating: 4.3,
    tags: ["Metabolismus", "Hubnutí", "Hormony"],
    emoji: "⚡",
  },

  // ==================== BOJOVÁ UMĚNÍ ====================
  {
    id: "tao-jeet-kune-do",
    title: "Tao of Jeet Kune Do",
    author: "Bruce Lee",
    category: "martial_arts",
    description: "Filozofie boje od legendárního Bruce Lee. Cesta zachycování pěstí - být jako voda.",
    pages: 208,
    rating: 4.8,
    tags: ["Filozofie", "Bruce Lee", "JKD"],
    emoji: "🐉",
  },
  {
    id: "meditations-on-violence",
    title: "Meditations on Violence",
    author: "Rory Miller",
    category: "martial_arts",
    description: "Realistický pohled na násilí a sebeobrana. Co funguje na ulici vs. v tělocvičně.",
    pages: 198,
    rating: 4.6,
    tags: ["Sebeobrna", "Realismus", "Psychologie"],
    emoji: "🛡️",
  },
  {
    id: "book-of-five-rings",
    title: "Kniha pěti kruhů",
    author: "Miyamoto Musashi",
    category: "martial_arts",
    description: "Klasické dílo legendárního samurajského šermíře o strategii boje i života.",
    pages: 192,
    rating: 4.7,
    tags: ["Samurai", "Strategie", "Klasika"],
    emoji: "⚔️",
  },

  // ==================== REGENERACE ====================
  {
    id: "sleep-book",
    title: "Sleep",
    author: "Nick Littlehales",
    category: "recovery",
    description: "Spánkový kouč sportovních hvězd odhaluje tajemství kvalitního spánku a regenerace.",
    pages: 224,
    rating: 4.4,
    tags: ["Spánek", "Regenerace", "Výkon"],
    emoji: "😴",
  },
  {
    id: "dychani",
    title: "Dýchání",
    author: "James Nestor",
    category: "recovery",
    description: "Ztracené umění dýchání. Jak správné dýchání změní tvůj spánek, výkon i zdraví.",
    pages: 304,
    rating: 4.6,
    tags: ["Dech", "Zdraví", "Nosní dýchání"],
    emoji: "🌬️",
  },
  {
    id: "becoming-supple-leopard",
    title: "Becoming a Supple Leopard",
    author: "Kelly Starrett",
    category: "recovery",
    description: "Ultimátní průvodce mobilitou a prevencí zranění. Řeš bolest pohybem, ne prášky.",
    pages: 400,
    rating: 4.5,
    tags: ["Mobilita", "Prevence", "Strečink"],
    emoji: "🐆",
  },
];

export function getBookById(id: string): FitnessBook | undefined {
  return booksData.find((b) => b.id === id);
}

export function getBooksByCategory(category: FitnessBook["category"]): FitnessBook[] {
  return booksData.filter((b) => b.category === category);
}

export const bookCategoryLabels: Record<FitnessBook["category"], string> = {
  fitness: "Fitness",
  mindset: "Mindset",
  nutrition: "Výživa",
  martial_arts: "Bojová umění",
  recovery: "Regenerace",
};
