import { Facility } from "@/types";

export const facilitiesData: Facility[] = [
  {
    id: "gym",
    type: "gym",
    name: "Posilovna",
    description: "Silový trénink, kardio zóna a skupinové lekce. Základna tvého fitness.",
    emoji: "🏋️",
    color: "#ff6b35",
    benefits: ["Silový trénink", "Kardio", "Skupinové lekce", "Osobní trenéři"],
    recommendedVisits: 12,
    visitUnit: "návštěv",
  },
  {
    id: "library",
    type: "library",
    name: "Knihovna",
    description: "Studium, sebevzdělávání a ticho na meditaci. Posiluj i svou mysl.",
    emoji: "📚",
    color: "#8b5cf6",
    benefits: ["Sebevzdělávání", "Soustředění", "Ticho na meditaci", "Přístup ke knihám"],
    recommendedVisits: 8,
    visitUnit: "návštěv",
  },
  {
    id: "physio",
    type: "physio",
    name: "Fyzioterapeut",
    description: "Prevence zranění, rehabilitace a mobilita. Investice do zdravého pohybového aparátu.",
    emoji: "🩺",
    color: "#10b981",
    benefits: ["Prevence zranění", "Rehabilitace", "Mobilita", "Korekce pohybových vzorců"],
    recommendedVisits: 6,
    visitUnit: "sezení",
  },
  {
    id: "nutritionist",
    type: "nutritionist",
    name: "Nutriční poradce",
    description: "Jídelníčky na míru, suplementace a analýza stravy. Výživa je 80 % výsledků.",
    emoji: "🥗",
    color: "#22c55e",
    benefits: ["Jídelníček na míru", "Suplementace", "Analýza stravy", "Nutriční plán"],
    recommendedVisits: 4,
    visitUnit: "sezení",
  },
  {
    id: "psychologist",
    type: "psychologist",
    name: "Psycholog / Kouč",
    description: "Motivace, stanovení cílů a mentální odolnost. Silná mysl = silné tělo.",
    emoji: "🧠",
    color: "#ec4899",
    benefits: ["Motivace", "Cíle", "Mentální odolnost", "Zvládání stresu"],
    recommendedVisits: 6,
    visitUnit: "sezení",
  },
  {
    id: "yoga",
    type: "yoga",
    name: "Jóga studio",
    description: "Flexibilita, dechová cvičení a meditace. Rovnováha těla i mysli.",
    emoji: "🧘",
    color: "#a855f7",
    benefits: ["Flexibilita", "Dechová cvičení", "Meditace", "Rovnováha"],
    recommendedVisits: 8,
    visitUnit: "lekcí",
  },
  {
    id: "pool",
    type: "pool",
    name: "Bazén",
    description: "Plavání, vodní regenerace a nízká zátěž kloubů. Ideální pro aktivní odpočinek.",
    emoji: "🏊",
    color: "#06b6d4",
    benefits: ["Plavání", "Regenerace", "Nízká zátěž kloubů", "Kardio bez dopadu"],
    recommendedVisits: 8,
    visitUnit: "návštěv",
  },
  {
    id: "coach",
    type: "coach",
    name: "Osobní trenér",
    description: "Individuální plány, korekce techniky a motivace. Nejrychlejší cesta k výsledkům.",
    emoji: "🎯",
    color: "#f59e0b",
    benefits: ["Individuální plán", "Korekce techniky", "Motivace", "Rychlejší výsledky"],
    recommendedVisits: 8,
    visitUnit: "lekcí",
  },
];

export function getFacilityById(id: string): Facility | undefined {
  return facilitiesData.find((f) => f.id === id);
}
