import { FoodItem } from '@/types';

// ==================== Komplexní databáze potravin ====================
// Nutriční hodnoty na 100g (pokud není uvedeno jinak)
// Hotová jídla mají hodnoty na 1 porci

export const foodDatabase: FoodItem[] = [
  // ==================== PROTEINOVÉ ZDROJE (12) ====================
  {
    id: 'food-protein-1',
    name: 'Kuřecí prsa',
    category: 'protein_source',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    emoji: '🍗',
    tags: ['kuře', 'drůbež', 'nízkotučné', 'vysokoproteinové', 'fitness'],
    servingSize: '100g',
    description: 'Klasická fitness potravina s vysokým obsahem bílkovin a nízkým tukem.',
  },
  {
    id: 'food-protein-2',
    name: 'Hovězí svíčková',
    category: 'protein_source',
    calories: 218,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
    emoji: '🥩',
    tags: ['hovězí', 'maso', 'železo', 'kreatin', 'steak'],
    servingSize: '100g',
    description: 'Prémiový kus hovězího masa bohatý na železo a kreatin.',
  },
  {
    id: 'food-protein-3',
    name: 'Losos',
    category: 'protein_source',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    emoji: '🐟',
    tags: ['ryba', 'omega-3', 'zdravé tuky', 'mořské plody'],
    servingSize: '100g',
    description: 'Tučná ryba bohatá na omega-3 mastné kyseliny a vitamin D.',
  },
  {
    id: 'food-protein-4',
    name: 'Tuňák',
    category: 'protein_source',
    calories: 132,
    protein: 28,
    carbs: 0,
    fat: 1.3,
    fiber: 0,
    emoji: '🐠',
    tags: ['ryba', 'konzerva', 'nízkotučné', 'vysokoproteinové'],
    servingSize: '100g',
    description: 'Libá ryba s jedním z nejvyšších poměrů bílkovin na kalorie.',
  },
  {
    id: 'food-protein-5',
    name: 'Vejce',
    category: 'protein_source',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    emoji: '🥚',
    tags: ['vejce', 'snídaně', 'kompletní protein', 'vitamín D'],
    servingSize: '100g (cca 2 ks)',
    description: 'Kompletní zdroj bílkovin s vysokou biologickou hodnotou.',
  },
  {
    id: 'food-protein-6',
    name: 'Tofu',
    category: 'protein_source',
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    emoji: '🧈',
    tags: ['vegan', 'sója', 'rostlinný protein', 'bezlepkové'],
    servingSize: '100g',
    description: 'Rostlinný zdroj bílkovin ze sóji, vhodný pro vegany.',
  },
  {
    id: 'food-protein-7',
    name: 'Tempeh',
    category: 'protein_source',
    calories: 192,
    protein: 20,
    carbs: 7.6,
    fat: 11,
    fiber: 4,
    emoji: '🫘',
    tags: ['vegan', 'fermentované', 'sója', 'probiotika'],
    servingSize: '100g',
    description: 'Fermentovaný sójový produkt s lepší stravitelností než tofu.',
  },
  {
    id: 'food-protein-8',
    name: 'Krevety',
    category: 'protein_source',
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    emoji: '🦐',
    tags: ['mořské plody', 'nízkotučné', 'jód', 'selen'],
    servingSize: '100g',
    description: 'Velmi nízkotučný zdroj kvalitního proteinu z moře.',
  },
  {
    id: 'food-protein-9',
    name: 'Krůtí prsa',
    category: 'protein_source',
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1.7,
    fiber: 0,
    emoji: '🦃',
    tags: ['drůbež', 'nízkotučné', 'vysokoproteinové', 'fitness'],
    servingSize: '100g',
    description: 'Ještě libější alternativa ke kuřecím prsům.',
  },
  {
    id: 'food-protein-10',
    name: 'Cottage sýr',
    category: 'protein_source',
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    emoji: '🧀',
    tags: ['mléčné', 'kasein', 'noční protein', 'svačina'],
    servingSize: '100g',
    description: 'Bohatý na kasein – ideální zdroj bílkovin před spaním.',
  },
  {
    id: 'food-protein-11',
    name: 'Řecký jogurt',
    category: 'protein_source',
    calories: 97,
    protein: 9,
    carbs: 3.6,
    fat: 5,
    fiber: 0,
    emoji: '🥛',
    tags: ['jogurt', 'probiotika', 'snídaně', 'svačina'],
    servingSize: '100g',
    description: 'Hustý jogurt s dvojnásobným obsahem bílkovin oproti běžnému.',
  },
  {
    id: 'food-protein-12',
    name: 'Treska',
    category: 'protein_source',
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    emoji: '🐟',
    tags: ['ryba', 'bílá ryba', 'nízkotučné', 'jemná chuť'],
    servingSize: '100g',
    description: 'Nízkotučná bílá ryba s jemnou chutí, ideální na dietu.',
  },

  // ==================== SACHARIDY (10) ====================
  {
    id: 'food-carb-1',
    name: 'Rýže basmati',
    category: 'carb_source',
    calories: 350,
    protein: 7.1,
    carbs: 78,
    fat: 0.6,
    fiber: 1.3,
    emoji: '🍚',
    tags: ['rýže', 'příloha', 'bezlepkové', 'základní'],
    servingSize: '100g (suchá)',
    description: 'Aromatická rýže s nižším glykemickým indexem.',
  },
  {
    id: 'food-carb-2',
    name: 'Ovesné vločky',
    category: 'carb_source',
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fat: 6.9,
    fiber: 10.6,
    emoji: '🥣',
    tags: ['ovesné', 'snídaně', 'vláknina', 'pomalé sacharidy', 'beta-glukan'],
    servingSize: '100g (suchá)',
    description: 'Výborný zdroj komplexních sacharidů a beta-glukanu.',
  },
  {
    id: 'food-carb-3',
    name: 'Sladké brambory',
    category: 'carb_source',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    emoji: '🍠',
    tags: ['batáty', 'příloha', 'vitamín A', 'bezlepkové', 'fitness'],
    servingSize: '100g',
    description: 'Výživnější alternativa k bramborám, bohaté na vitamín A.',
  },
  {
    id: 'food-carb-4',
    name: 'Quinoa',
    category: 'carb_source',
    calories: 368,
    protein: 14.1,
    carbs: 64,
    fat: 6.1,
    fiber: 7,
    emoji: '🌾',
    tags: ['pseudoobiloviny', 'kompletní protein', 'bezlepkové', 'superfood'],
    servingSize: '100g (suchá)',
    description: 'Pseudoobilovina s kompletním aminokyselinovým profilem.',
  },
  {
    id: 'food-carb-5',
    name: 'Celozrnné těstoviny',
    category: 'carb_source',
    calories: 348,
    protein: 13,
    carbs: 68,
    fat: 2.5,
    fiber: 7.5,
    emoji: '🍝',
    tags: ['těstoviny', 'celozrnné', 'vláknina', 'příloha'],
    servingSize: '100g (suchá)',
    description: 'Celozrnná varianta těstovin s vyšším obsahem vlákniny.',
  },
  {
    id: 'food-carb-6',
    name: 'Pšeničný chléb',
    category: 'carb_source',
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
    emoji: '🍞',
    tags: ['pečivo', 'snídaně', 'běžné'],
    servingSize: '100g',
    description: 'Klasický bílý pšeničný chléb, rychlý zdroj energie.',
  },
  {
    id: 'food-carb-7',
    name: 'Pohanka',
    category: 'carb_source',
    calories: 343,
    protein: 13.3,
    carbs: 72,
    fat: 3.4,
    fiber: 10,
    emoji: '🌾',
    tags: ['bezlepkové', 'česká kuchyně', 'rutin', 'příloha'],
    servingSize: '100g (suchá)',
    description: 'Tradiční česká příloha bohatá na rutin a minerály.',
  },
  {
    id: 'food-carb-8',
    name: 'Bulgur',
    category: 'carb_source',
    calories: 342,
    protein: 12.3,
    carbs: 76,
    fat: 1.3,
    fiber: 12.5,
    emoji: '🌾',
    tags: ['obilnina', 'příloha', 'vláknina', 'blízký východ'],
    servingSize: '100g (suchá)',
    description: 'Lámané pšeničné zrno s vysokým obsahem vlákniny.',
  },
  {
    id: 'food-carb-9',
    name: 'Kuskus',
    category: 'carb_source',
    calories: 376,
    protein: 12.8,
    carbs: 77,
    fat: 0.6,
    fiber: 5,
    emoji: '🍚',
    tags: ['příloha', 'rychlá příprava', 'severní Afrika'],
    servingSize: '100g (suchá)',
    description: 'Lehká příloha z tvrdé pšenice, připravená za pár minut.',
  },
  {
    id: 'food-carb-10',
    name: 'Černý chléb',
    category: 'carb_source',
    calories: 250,
    protein: 8.5,
    carbs: 48,
    fat: 2.4,
    fiber: 6.5,
    emoji: '🍞',
    tags: ['žitný', 'pečivo', 'vláknina', 'česká kuchyně'],
    servingSize: '100g',
    description: 'Tmavý žitný chléb s vyšším obsahem vlákniny a minerálů.',
  },

  // ==================== TUKY (8) ====================
  {
    id: 'food-fat-1',
    name: 'Avokádo',
    category: 'fat_source',
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    emoji: '🥑',
    tags: ['zdravé tuky', 'draslík', 'vláknina', 'superfood'],
    servingSize: '100g',
    description: 'Bohaté na mononenasycené tuky a draslík.',
  },
  {
    id: 'food-fat-2',
    name: 'Olivový olej',
    category: 'fat_source',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    emoji: '🫒',
    tags: ['olej', 'středomořská dieta', 'mononenasycené tuky', 'vaření'],
    servingSize: '100g (cca 7 lžic)',
    description: 'Základ středomořské diety, bohatý na antioxidanty.',
  },
  {
    id: 'food-fat-3',
    name: 'Ořechy (vlašské)',
    category: 'fat_source',
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    emoji: '🥜',
    tags: ['ořechy', 'omega-3', 'mozek', 'svačina'],
    servingSize: '100g',
    description: 'Vynikající zdroj rostlinných omega-3 mastných kyselin.',
  },
  {
    id: 'food-fat-4',
    name: 'Mandle',
    category: 'fat_source',
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    emoji: '🌰',
    tags: ['ořechy', 'vitamín E', 'hořčík', 'svačina'],
    servingSize: '100g',
    description: 'Bohaté na vitamín E, hořčík a zdravé tuky.',
  },
  {
    id: 'food-fat-5',
    name: 'Arašídové máslo',
    category: 'fat_source',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    emoji: '🥜',
    tags: ['pomazánka', 'protein', 'bulking', 'energie'],
    servingSize: '100g',
    description: 'Oblíbená pomazánka fitness nadšenců, kombinace tuků a bílkovin.',
  },
  {
    id: 'food-fat-6',
    name: 'Kokosový olej',
    category: 'fat_source',
    calories: 862,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    emoji: '🥥',
    tags: ['olej', 'MCT', 'vaření', 'nasycené tuky'],
    servingSize: '100g (cca 7 lžic)',
    description: 'Obsahuje MCT tuky, které se rychle přeměňují na energii.',
  },
  {
    id: 'food-fat-7',
    name: 'Lněná semínka',
    category: 'fat_source',
    calories: 534,
    protein: 18.3,
    carbs: 28.9,
    fat: 42.2,
    fiber: 27.3,
    emoji: '🌱',
    tags: ['semínka', 'omega-3', 'vláknina', 'vegan'],
    servingSize: '100g',
    description: 'Nejbohatší rostlinný zdroj omega-3, extrémně vysoká vláknina.',
  },
  {
    id: 'food-fat-8',
    name: 'Chia semínka',
    category: 'fat_source',
    calories: 486,
    protein: 16.5,
    carbs: 42.1,
    fat: 30.7,
    fiber: 34.4,
    emoji: '🫘',
    tags: ['semínka', 'omega-3', 'superfood', 'pudink', 'vláknina'],
    servingSize: '100g',
    description: 'Superfood s výjimečným obsahem vlákniny a omega-3.',
  },

  // ==================== ZELENINA (12) ====================
  {
    id: 'food-veg-1',
    name: 'Brokolice',
    category: 'vegetable',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    emoji: '🥦',
    tags: ['zelenina', 'vitamín C', 'vláknina', 'fitness', 'antioxidanty'],
    servingSize: '100g',
    description: 'Královna fitness zeleniny, bohatá na vitamín C a sulforafan.',
  },
  {
    id: 'food-veg-2',
    name: 'Špenát',
    category: 'vegetable',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    emoji: '🥬',
    tags: ['listová zelenina', 'železo', 'hořčík', 'salát'],
    servingSize: '100g',
    description: 'Nutrient-dense listová zelenina bohatá na železo a kyselinu listovou.',
  },
  {
    id: 'food-veg-3',
    name: 'Kapusta (kale)',
    category: 'vegetable',
    calories: 49,
    protein: 4.3,
    carbs: 8.8,
    fat: 0.9,
    fiber: 3.6,
    emoji: '🥬',
    tags: ['superfood', 'vitamín K', 'antioxidanty', 'smoothie'],
    servingSize: '100g',
    description: 'Superfood s mimořádnou nutriční hustotou a antioxidanty.',
  },
  {
    id: 'food-veg-4',
    name: 'Rajčata',
    category: 'vegetable',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    emoji: '🍅',
    tags: ['lykopen', 'salát', 'omáčka', 'univerzální'],
    servingSize: '100g',
    description: 'Bohaté na lykopen – silný antioxidant chránící buňky.',
  },
  {
    id: 'food-veg-5',
    name: 'Okurky',
    category: 'vegetable',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    emoji: '🥒',
    tags: ['hydratace', 'nízkokalorické', 'salát', 'svačina'],
    servingSize: '100g',
    description: 'Extrémně nízkokalorická zelenina s vysokým obsahem vody.',
  },
  {
    id: 'food-veg-6',
    name: 'Paprika',
    category: 'vegetable',
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    emoji: '🌶️',
    tags: ['vitamín C', 'antioxidanty', 'barevná', 'salát'],
    servingSize: '100g',
    description: 'Obsahuje více vitamínu C než pomeranč.',
  },
  {
    id: 'food-veg-7',
    name: 'Cuketa',
    category: 'vegetable',
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    emoji: '🥒',
    tags: ['nízkokalorické', 'příloha', 'zoodles', 'grilování'],
    servingSize: '100g',
    description: 'Lehká zelenina, skvělá náhrada těstovin (zoodles).',
  },
  {
    id: 'food-veg-8',
    name: 'Mrkev',
    category: 'vegetable',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    emoji: '🥕',
    tags: ['beta-karoten', 'vitamín A', 'svačina', 'sladká'],
    servingSize: '100g',
    description: 'Nejlepší zdroj beta-karotenu, důležitého pro zrak.',
  },
  {
    id: 'food-veg-9',
    name: 'Květák',
    category: 'vegetable',
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
    emoji: '🥦',
    tags: ['nízkokalorické', 'low-carb', 'náhrada rýže', 'univerzální'],
    servingSize: '100g',
    description: 'Univerzální zelenina, populární low-carb náhrada rýže.',
  },
  {
    id: 'food-veg-10',
    name: 'Červená řepa',
    category: 'vegetable',
    calories: 43,
    protein: 1.6,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    emoji: '🫐',
    tags: ['dusičnany', 'výkon', 'pre-workout', 'krev'],
    servingSize: '100g',
    description: 'Přírodní zdroj dusičnanů zlepšujících sportovní výkon.',
  },
  {
    id: 'food-veg-11',
    name: 'Chřest',
    category: 'vegetable',
    calories: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    emoji: '🌿',
    tags: ['diuretikum', 'detox', 'vitamín K', 'jaro'],
    servingSize: '100g',
    description: 'Přirozené diuretikum, pomáhá zbavovat se přebytečné vody.',
  },
  {
    id: 'food-veg-12',
    name: 'Zelené fazolky',
    category: 'vegetable',
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    fiber: 3.4,
    emoji: '🫛',
    tags: ['příloha', 'vláknina', 'vitamíny', 'sytící'],
    servingSize: '100g',
    description: 'Nízkokalorická příloha s dobrým obsahem vlákniny.',
  },

  // ==================== OVOCE (10) ====================
  {
    id: 'food-fruit-1',
    name: 'Banán',
    category: 'fruit',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    emoji: '🍌',
    tags: ['draslík', 'energie', 'pre-workout', 'rychlé sacharidy'],
    servingSize: '100g (cca 1 ks)',
    description: 'Ideální rychlý zdroj energie před tréninkem.',
  },
  {
    id: 'food-fruit-2',
    name: 'Jablko',
    category: 'fruit',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    emoji: '🍎',
    tags: ['vláknina', 'pektin', 'svačina', 'české'],
    servingSize: '100g (cca 1 menší ks)',
    description: 'Klasické české ovoce bohaté na pektin a antioxidanty.',
  },
  {
    id: 'food-fruit-3',
    name: 'Borůvky',
    category: 'fruit',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    emoji: '🫐',
    tags: ['antioxidanty', 'superfood', 'smoothie', 'mozek'],
    servingSize: '100g',
    description: 'Jedny z nejsilnějších přírodních antioxidantů.',
  },
  {
    id: 'food-fruit-4',
    name: 'Jahody',
    category: 'fruit',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    emoji: '🍓',
    tags: ['vitamín C', 'nízkokalorické', 'dezert', 'léto'],
    servingSize: '100g',
    description: 'Nízkokalorické ovoce s vysokým obsahem vitamínu C.',
  },
  {
    id: 'food-fruit-5',
    name: 'Pomeranč',
    category: 'fruit',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    emoji: '🍊',
    tags: ['vitamín C', 'imunita', 'citrus', 'džus'],
    servingSize: '100g',
    description: 'Klasický zdroj vitamínu C pro podporu imunity.',
  },
  {
    id: 'food-fruit-6',
    name: 'Kiwi',
    category: 'fruit',
    calories: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3,
    emoji: '🥝',
    tags: ['vitamín C', 'vitamín K', 'trávení', 'actinidin'],
    servingSize: '100g',
    description: 'Obsahuje víc vitamínu C než pomeranč a enzymy na trávení.',
  },
  {
    id: 'food-fruit-7',
    name: 'Mango',
    category: 'fruit',
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    emoji: '🥭',
    tags: ['tropické', 'vitamín A', 'smoothie', 'sladké'],
    servingSize: '100g',
    description: 'Sladké tropické ovoce bohaté na vitamíny A a C.',
  },
  {
    id: 'food-fruit-8',
    name: 'Ananas',
    category: 'fruit',
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    emoji: '🍍',
    tags: ['bromelain', 'trávení', 'tropické', 'protizánětlivé'],
    servingSize: '100g',
    description: 'Obsahuje bromelain – enzym podporující trávení bílkovin.',
  },
  {
    id: 'food-fruit-9',
    name: 'Hroznové víno',
    category: 'fruit',
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    emoji: '🍇',
    tags: ['resveratrol', 'antioxidanty', 'svačina', 'energie'],
    servingSize: '100g',
    description: 'Zdroj resveratrolu a rychlé energie z přírodních cukrů.',
  },
  {
    id: 'food-fruit-10',
    name: 'Vodní meloun',
    category: 'fruit',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    emoji: '🍉',
    tags: ['hydratace', 'nízkokalorické', 'léto', 'citrulin'],
    servingSize: '100g',
    description: 'Skvělá hydratace, obsahuje citrulin pro lepší prokrvení svalů.',
  },

  // ==================== MLÉČNÉ VÝROBKY (6) ====================
  {
    id: 'food-dairy-1',
    name: 'Mléko plnotučné',
    category: 'dairy',
    calories: 64,
    protein: 3.3,
    carbs: 4.8,
    fat: 3.6,
    fiber: 0,
    emoji: '🥛',
    tags: ['mléko', 'vápník', 'vitamín D', 'základní'],
    servingSize: '100ml',
    description: 'Klasický zdroj vápníku a kvalitního živočišného proteinu.',
  },
  {
    id: 'food-dairy-2',
    name: 'Mléko odstředěné',
    category: 'dairy',
    calories: 35,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    emoji: '🥛',
    tags: ['mléko', 'nízkokalorické', 'vápník', 'dieta'],
    servingSize: '100ml',
    description: 'Odtučněné mléko pro ty, kteří hlídají příjem tuků.',
  },
  {
    id: 'food-dairy-3',
    name: 'Tvaroh',
    category: 'dairy',
    calories: 105,
    protein: 13,
    carbs: 3.5,
    fat: 4.5,
    fiber: 0,
    emoji: '🧀',
    tags: ['tvaroh', 'česká klasika', 'kasein', 'vysokoproteinové'],
    servingSize: '100g',
    description: 'Česká fitness klasika s vysokým obsahem kaseinu.',
  },
  {
    id: 'food-dairy-4',
    name: 'Kefír',
    category: 'dairy',
    calories: 56,
    protein: 3.3,
    carbs: 4.7,
    fat: 2.5,
    fiber: 0,
    emoji: '🥛',
    tags: ['probiotika', 'fermentované', 'střevní zdraví', 'imunita'],
    servingSize: '100ml',
    description: 'Fermentovaný mléčný nápoj plný probiotik pro zdravá střeva.',
  },
  {
    id: 'food-dairy-5',
    name: 'Skyr',
    category: 'dairy',
    calories: 63,
    protein: 11,
    carbs: 3.8,
    fat: 0.2,
    fiber: 0,
    emoji: '🥛',
    tags: ['islandský', 'vysokoproteinové', 'nízkokalorické', 'fitness'],
    servingSize: '100g',
    description: 'Islandský mléčný výrobek s vysokým proteinem a minimem tuku.',
  },
  {
    id: 'food-dairy-6',
    name: 'Bílý jogurt',
    category: 'dairy',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    emoji: '🥛',
    tags: ['jogurt', 'probiotika', 'snídaně', 'univerzální'],
    servingSize: '100g',
    description: 'Univerzální mléčný výrobek vhodný do mnoha receptů.',
  },

  // ==================== SVAČINY / SNACKY (8) ====================
  {
    id: 'food-snack-1',
    name: 'Proteinová tyčinka',
    category: 'snack',
    calories: 220,
    protein: 20,
    carbs: 25,
    fat: 8,
    fiber: 3,
    emoji: '🍫',
    tags: ['protein', 'pohodlné', 'po tréninku', 'svačina'],
    servingSize: '1 ks (60g)',
    description: 'Pohodlný zdroj proteinu na cesty a po tréninku.',
  },
  {
    id: 'food-snack-2',
    name: 'Rýžové vafle',
    category: 'snack',
    calories: 387,
    protein: 8,
    carbs: 82,
    fat: 2.8,
    fiber: 4.2,
    emoji: '🍘',
    tags: ['nízkokalorické', 'křupavé', 'bezlepkové', 'dieta'],
    servingSize: '100g (1 ks = cca 9g)',
    description: 'Lehká svačinka, ideální základ pro různé pomazánky.',
  },
  {
    id: 'food-snack-3',
    name: 'Hummus',
    category: 'snack',
    calories: 166,
    protein: 7.9,
    carbs: 14.3,
    fat: 9.6,
    fiber: 6,
    emoji: '🫘',
    tags: ['cizrna', 'vegan', 'dip', 'blízký východ', 'vláknina'],
    servingSize: '100g',
    description: 'Krémový dip z cizrny bohatý na bílkoviny a vlákninu.',
  },
  {
    id: 'food-snack-4',
    name: 'Trail mix',
    category: 'snack',
    calories: 462,
    protein: 14,
    carbs: 44,
    fat: 29,
    fiber: 5,
    emoji: '🥜',
    tags: ['ořechy', 'sušené ovoce', 'energie', 'turistika'],
    servingSize: '100g',
    description: 'Směs ořechů a sušeného ovoce, skvělý zdroj energie.',
  },
  {
    id: 'food-snack-5',
    name: 'Tmavá čokoláda',
    category: 'snack',
    calories: 546,
    protein: 4.9,
    carbs: 60,
    fat: 31,
    fiber: 7,
    emoji: '🍫',
    tags: ['antioxidanty', 'hořčík', 'dezert', 'nálada', '70%+'],
    servingSize: '100g',
    description: 'Tmavá čokoláda (70%+) s antioxidanty a hořčíkem.',
  },
  {
    id: 'food-snack-6',
    name: 'Edamame',
    category: 'snack',
    calories: 121,
    protein: 11,
    carbs: 8.6,
    fat: 5.2,
    fiber: 5.2,
    emoji: '🫛',
    tags: ['sója', 'protein', 'vegan', 'asijská kuchyně'],
    servingSize: '100g',
    description: 'Mladé sójové boby, skvělá proteinová svačinka.',
  },
  {
    id: 'food-snack-7',
    name: 'Beef jerky',
    category: 'snack',
    calories: 250,
    protein: 33,
    carbs: 11,
    fat: 8,
    fiber: 0.5,
    emoji: '🥩',
    tags: ['sušené maso', 'protein', 'přenosné', 'low-carb'],
    servingSize: '100g',
    description: 'Sušené hovězí maso s extrémně vysokým obsahem bílkovin.',
  },
  {
    id: 'food-snack-8',
    name: 'Proteinový pudink',
    category: 'snack',
    calories: 80,
    protein: 10,
    carbs: 8,
    fat: 1.5,
    fiber: 0.5,
    emoji: '🍮',
    tags: ['protein', 'dezert', 'nízkokalorické', 'sladké'],
    servingSize: '100g (1 kelímek = 200g)',
    description: 'Nízkokalorický proteinový dezert pro sladkou chuť.',
  },

  // ==================== HOTOVÁ JÍDLA / RECEPTY (15) ====================
  // Hodnoty na 1 porci
  {
    id: 'food-meal-1',
    name: 'Kuřecí prsa s rýží',
    category: 'meal',
    calories: 450,
    protein: 42,
    carbs: 50,
    fat: 6,
    fiber: 2,
    emoji: '🍗',
    tags: ['fitness klasika', 'meal prep', 'oběd', 'jednoduché'],
    servingSize: '1 porce (350g)',
    description: 'Klasické fitness jídlo – 200g kuřete + 150g vařené rýže.',
  },
  {
    id: 'food-meal-2',
    name: 'Losos s batáty',
    category: 'meal',
    calories: 520,
    protein: 35,
    carbs: 40,
    fat: 22,
    fiber: 5,
    emoji: '🐟',
    tags: ['omega-3', 'oběd', 'zdravé tuky', 'výživné'],
    servingSize: '1 porce (400g)',
    description: '150g lososa s 200g pečených sladkých brambor a zeleninou.',
  },
  {
    id: 'food-meal-3',
    name: 'Proteinová omeleta',
    category: 'meal',
    calories: 380,
    protein: 32,
    carbs: 5,
    fat: 26,
    fiber: 1,
    emoji: '🍳',
    tags: ['snídaně', 'low-carb', 'rychlé', 'vejce'],
    servingSize: '1 porce (250g)',
    description: 'Omeleta ze 3 vajec se šunkou, sýrem a zeleninou.',
  },
  {
    id: 'food-meal-4',
    name: 'Overnight oats',
    category: 'meal',
    calories: 350,
    protein: 15,
    carbs: 52,
    fat: 10,
    fiber: 7,
    emoji: '🥣',
    tags: ['snídaně', 'příprava předem', 'ovesné', 'studené'],
    servingSize: '1 porce (300g)',
    description: 'Ovesné vločky naložené přes noc v jogurtu s ovocem.',
  },
  {
    id: 'food-meal-5',
    name: 'Buddha bowl',
    category: 'meal',
    calories: 480,
    protein: 22,
    carbs: 55,
    fat: 18,
    fiber: 12,
    emoji: '🥗',
    tags: ['vegan friendly', 'vyvážené', 'zelenina', 'quinoa'],
    servingSize: '1 porce (450g)',
    description: 'Quinoa, avokádo, cizrna, zelenina a tahini dresink.',
  },
  {
    id: 'food-meal-6',
    name: 'Řecký salát',
    category: 'meal',
    calories: 280,
    protein: 12,
    carbs: 12,
    fat: 20,
    fiber: 4,
    emoji: '🥗',
    tags: ['salát', 'lehké', 'feta', 'středomořské', 'léto'],
    servingSize: '1 porce (300g)',
    description: 'Rajčata, okurky, olivy, feta a olivový olej.',
  },
  {
    id: 'food-meal-7',
    name: 'Kuřecí wrap',
    category: 'meal',
    calories: 420,
    protein: 35,
    carbs: 38,
    fat: 14,
    fiber: 4,
    emoji: '🌯',
    tags: ['oběd', 'přenosné', 'tortilla', 'kuře'],
    servingSize: '1 porce (280g)',
    description: 'Celozrnná tortilla s kuřecím masem, zeleninou a dresinkem.',
  },
  {
    id: 'food-meal-8',
    name: 'Hovězí steak s bramborami',
    category: 'meal',
    calories: 580,
    protein: 45,
    carbs: 35,
    fat: 25,
    fiber: 4,
    emoji: '🥩',
    tags: ['hovězí', 'večeře', 'kreatin', 'železo'],
    servingSize: '1 porce (400g)',
    description: '200g hovězího steaku s pečenými bramborami a zeleninou.',
  },
  {
    id: 'food-meal-9',
    name: 'Tuňákový salát',
    category: 'meal',
    calories: 320,
    protein: 35,
    carbs: 10,
    fat: 15,
    fiber: 3,
    emoji: '🥗',
    tags: ['salát', 'vysokoproteinové', 'lehké', 'dieta'],
    servingSize: '1 porce (350g)',
    description: 'Tuňák s listovým salátem, vejcem a lehkým dresinkem.',
  },
  {
    id: 'food-meal-10',
    name: 'Protein pancakes',
    category: 'meal',
    calories: 340,
    protein: 28,
    carbs: 35,
    fat: 9,
    fiber: 3,
    emoji: '🥞',
    tags: ['snídaně', 'proteinové', 'palačinky', 'sladké'],
    servingSize: '1 porce (200g, 3 ks)',
    description: 'Palačinky z ovesných vloček, vajec a proteinového prášku.',
  },
  {
    id: 'food-meal-11',
    name: 'Smoothie bowl',
    category: 'meal',
    calories: 310,
    protein: 12,
    carbs: 48,
    fat: 8,
    fiber: 6,
    emoji: '🥣',
    tags: ['snídaně', 'ovoce', 'smoothie', 'superfood'],
    servingSize: '1 porce (350g)',
    description: 'Hustý ovocný smoothie s toppingy – granola, ovoce, semínka.',
  },
  {
    id: 'food-meal-12',
    name: 'Chilli con carne',
    category: 'meal',
    calories: 410,
    protein: 30,
    carbs: 30,
    fat: 18,
    fiber: 8,
    emoji: '🌶️',
    tags: ['hovězí', 'fazole', 'mexické', 'sytící', 'meal prep'],
    servingSize: '1 porce (400g)',
    description: 'Hovězí maso s fazolemi, rajčaty a kořením – sytící klasika.',
  },
  {
    id: 'food-meal-13',
    name: 'Kuřecí stir-fry',
    category: 'meal',
    calories: 390,
    protein: 35,
    carbs: 30,
    fat: 14,
    fiber: 5,
    emoji: '🍜',
    tags: ['asijské', 'kuře', 'zelenina', 'wok', 'rychlé'],
    servingSize: '1 porce (400g)',
    description: 'Kuřecí kousky s wok zeleninou a sójovou omáčkou.',
  },
  {
    id: 'food-meal-14',
    name: 'Lososový poke bowl',
    category: 'meal',
    calories: 490,
    protein: 30,
    carbs: 50,
    fat: 18,
    fiber: 5,
    emoji: '🍣',
    tags: ['havajské', 'losos', 'rýže', 'trendy', 'omega-3'],
    servingSize: '1 porce (400g)',
    description: 'Sushi rýže s čerstvým lososem, avokádem a edamame.',
  },
  {
    id: 'food-meal-15',
    name: 'Fitness pizza',
    category: 'meal',
    calories: 440,
    protein: 35,
    carbs: 42,
    fat: 14,
    fiber: 5,
    emoji: '🍕',
    tags: ['pizza', 'fitness verze', 'celozrnné', 'kuřecí'],
    servingSize: '1 porce (300g)',
    description: 'Celozrnné těsto s kuřecím masem, zeleninou a light mozzarellou.',
  },
];

// ==================== Pomocné funkce ====================

export function getFoodsByCategory(category: FoodItem['category']): FoodItem[] {
  return foodDatabase.filter(f => f.category === category);
}

export function getFoodById(id: string): FoodItem | undefined {
  return foodDatabase.find(f => f.id === id);
}

export function searchFoods(query: string): FoodItem[] {
  const q = query.toLowerCase();
  return foodDatabase.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.tags.some(t => t.toLowerCase().includes(q))
  );
}

export function getHighProteinFoods(minProtein = 20): FoodItem[] {
  return foodDatabase
    .filter(f => f.protein >= minProtein)
    .sort((a, b) => b.protein - a.protein);
}

export const foodCategories = [
  { id: 'protein_source', name: 'Proteiny', emoji: '🥩' },
  { id: 'carb_source', name: 'Sacharidy', emoji: '🍚' },
  { id: 'fat_source', name: 'Zdravé tuky', emoji: '🥑' },
  { id: 'vegetable', name: 'Zelenina', emoji: '🥦' },
  { id: 'fruit', name: 'Ovoce', emoji: '🍎' },
  { id: 'dairy', name: 'Mléčné výrobky', emoji: '🥛' },
  { id: 'snack', name: 'Svačiny', emoji: '🍫' },
  { id: 'meal', name: 'Hotová jídla', emoji: '🍽️' },
] as const;
