import { BodyPartPlan } from "@/types";

const allPlans: BodyPartPlan[] = [
  // ==================== BŘICHO (abs) ====================
  {
    id: "abs-beginner",
    bodyPartId: "abs",
    name: "Pevné břicho - Základ",
    description: "Jemný start pro úplné začátečníky. Žádné vybavení, postupný nárůst.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["abs-1", "abs-4", "abs-5"],
    rating: 4.6,
    ratingCount: 127,
    tags: ["Domácí", "Bez vybavení", "Začátečník"],
    estimatedMinutes: 15,
    weeklyProgression: [
      "Týden 1-2: 2 série × 10 opakování, odpočinek 60s",
      "Týden 3-4: 3 série × 12 opakování, odpočinek 45s",
      "Týden 5-6: 3 série × 15 opakování, odpočinek 30s",
    ],
  },
  {
    id: "abs-intense",
    bodyPartId: "abs",
    name: "Ocelové břicho",
    description: "Intenzivní program pro viditelné výsledky. Mix dynamických a statických cviků.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 4,
    exercises: ["abs-1", "abs-3", "abs-5", "abs-6"],
    rating: 4.3,
    ratingCount: 85,
    tags: ["Náročnější", "Medicinbal volitelný"],
    estimatedMinutes: 25,
    weeklyProgression: [
      "Týden 1-2: 2 série × 12 opakování, odpočinek 60s",
      "Týden 3-4: 3 série × 15 opakování, odpočinek 45s",
      "Týden 5-6: 4 série × 15 opakování, odpočinek 30s",
      "Týden 7-8: 4 série × 20 opakování, odpočinek 30s",
    ],
  },
  {
    id: "abs-quick",
    bodyPartId: "abs",
    name: "5-minutové břicho",
    description: "Rychlý denní program. Jen 5 minut, ale každý den. Pro ty co nemají čas.",
    difficulty: "Začátečník",
    durationWeeks: 4,
    frequencyPerWeek: 5,
    exercises: ["abs-1", "abs-4"],
    rating: 4.1,
    ratingCount: 203,
    tags: ["Rychlý", "Denní", "5 minut"],
    estimatedMinutes: 5,
    weeklyProgression: [
      "Týden 1: 2 série × 10 opakování",
      "Týden 2: 2 série × 15 opakování",
      "Týden 3: 3 série × 12 opakování",
      "Týden 4: 3 série × 15 opakování",
    ],
  },

  // ==================== KRČNÍ PÁTEŘ (neck) ====================
  {
    id: "neck-beginner",
    bodyPartId: "neck",
    name: "Zdravá šíje - Start",
    description: "Prevence bolestí krční páteře. Ideální pro lidi u počítače.",
    difficulty: "Začátečník",
    durationWeeks: 4,
    frequencyPerWeek: 4,
    exercises: ["neck-1", "neck-2", "neck-3"],
    rating: 4.7,
    ratingCount: 94,
    tags: ["Domácí", "Prevence", "Kancelář"],
    estimatedMinutes: 10,
    weeklyProgression: [
      "Týden 1: 2 série × 8 opakování, výdrže 5s",
      "Týden 2: 2 série × 10 opakování, výdrže 8s",
      "Týden 3: 3 série × 10 opakování, výdrže 10s",
      "Týden 4: 3 série × 12 opakování, výdrže 10s",
    ],
  },
  {
    id: "neck-mobility",
    bodyPartId: "neck",
    name: "Mobilita krku",
    description: "Zaměřeno na rozsah pohybu a uvolnění napětí. Skvělé po práci.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["neck-2", "neck-3"],
    rating: 4.4,
    ratingCount: 62,
    tags: ["Relaxace", "Mobilita", "Po práci"],
    estimatedMinutes: 8,
    weeklyProgression: [
      "Týden 1-2: 2 série, pomalé pohyby, 5s výdrže",
      "Týden 3-4: 3 série, plný rozsah pohybu, 8s výdrže",
      "Týden 5-6: 3 série, přidat odpor rukou, 10s výdrže",
    ],
  },

  // ==================== RAMENA (shoulders) ====================
  {
    id: "shoulders-beginner",
    bodyPartId: "shoulders",
    name: "Pevná ramena - Základ",
    description: "Budování stabilních ramen bez těžkých vah. Ideální pro začátečníky.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["shoulders-3", "shoulders-5"],
    rating: 4.5,
    ratingCount: 108,
    tags: ["Domácí", "Bez vybavení", "Stabilita"],
    estimatedMinutes: 20,
    weeklyProgression: [
      "Týden 1-2: 2 série × 10 opakování, odpočinek 60s",
      "Týden 3-4: 3 série × 12 opakování, odpočinek 45s",
      "Týden 5-6: 3 série × 15 opakování, odpočinek 30s",
    ],
  },
  {
    id: "shoulders-builder",
    bodyPartId: "shoulders",
    name: "Kulatá ramena",
    description: "Komplexní program pro všechny hlavy deltového svalu. S jednoručkami.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 3,
    exercises: ["shoulders-1", "shoulders-2", "shoulders-3", "shoulders-4"],
    rating: 4.4,
    ratingCount: 76,
    tags: ["Jednoručky", "Objem", "Kompletní"],
    estimatedMinutes: 30,
    weeklyProgression: [
      "Týden 1-2: 3 série × 10 opakování, lehčí váhy",
      "Týden 3-4: 3 série × 12 opakování, střední váhy",
      "Týden 5-6: 4 série × 10 opakování, těžší váhy",
      "Týden 7-8: 4 série × 12 opakování, progresivní přetížení",
    ],
  },

  // ==================== PRSA (chest) ====================
  {
    id: "chest-beginner",
    bodyPartId: "chest",
    name: "Silná prsa - Start",
    description: "Od nuly k prvním klíkům. Postupný program bez vybavení.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["chest-2", "chest-5", "chest-6"],
    rating: 4.5,
    ratingCount: 142,
    tags: ["Domácí", "Bez vybavení", "Kliky"],
    estimatedMinutes: 20,
    weeklyProgression: [
      "Týden 1-2: Kliky na kolenou, 3 série × 8",
      "Týden 3-4: Mix kliky na kolenou a plné, 3 série × 10",
      "Týden 5-6: Plné kliky, 3 série × 12 + varianty",
    ],
  },
  {
    id: "chest-mass",
    bodyPartId: "chest",
    name: "Mohutná prsa",
    description: "Program pro objem prsních svalů. Vyžaduje činku a lavici.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 3,
    exercises: ["chest-1", "chest-3", "chest-4", "chest-7"],
    rating: 4.6,
    ratingCount: 98,
    tags: ["Posilovna", "Objem", "Činka"],
    estimatedMinutes: 35,
    weeklyProgression: [
      "Týden 1-2: 3 série × 10, seznámení s pohyby",
      "Týden 3-4: 3 série × 12, zvýšení váhy",
      "Týden 5-6: 4 série × 10, těžší váhy",
      "Týden 7-8: 4 série × 8-12, pyramidové série",
    ],
  },
  {
    id: "chest-home",
    bodyPartId: "chest",
    name: "Prsa doma",
    description: "Efektivní trénink prsou jen s vlastní váhou. Žádné vybavení.",
    difficulty: "Začátečník",
    durationWeeks: 4,
    frequencyPerWeek: 4,
    exercises: ["chest-2", "chest-5", "chest-6"],
    rating: 4.2,
    ratingCount: 167,
    tags: ["Domácí", "Rychlý", "Bez vybavení"],
    estimatedMinutes: 15,
    weeklyProgression: [
      "Týden 1: 2 série × 8 každý cvik",
      "Týden 2: 3 série × 8 každý cvik",
      "Týden 3: 3 série × 10 každý cvik",
      "Týden 4: 3 série × 12 každý cvik",
    ],
  },

  // ==================== RUCE (arms) ====================
  {
    id: "arms-beginner",
    bodyPartId: "arms",
    name: "Silné ruce - Základ",
    description: "Vybuduj si biceps a triceps od základů. Jednoduché cviky, velké výsledky.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["arms-2", "arms-3", "arms-5"],
    rating: 4.4,
    ratingCount: 115,
    tags: ["Začátečník", "Jednoručky", "Expandéry"],
    estimatedMinutes: 20,
    weeklyProgression: [
      "Týden 1-2: 2 série × 12 opakování, lehké váhy",
      "Týden 3-4: 3 série × 12 opakování, střední váhy",
      "Týden 5-6: 3 série × 15 opakování, zvýšení zátěže",
    ],
  },
  {
    id: "arms-pump",
    bodyPartId: "arms",
    name: "Nabitý bicák",
    description: "Intenzivní arm day pro maximální pump. Biceps + triceps v jednom.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 3,
    exercises: ["arms-1", "arms-2", "arms-3", "arms-4"],
    rating: 4.5,
    ratingCount: 89,
    tags: ["Posilovna", "Objem", "Pump"],
    estimatedMinutes: 30,
    weeklyProgression: [
      "Týden 1-2: 3 série × 10, základ techniky",
      "Týden 3-4: 3 série × 12, superset biceps/triceps",
      "Týden 5-6: 4 série × 10, drop sety",
      "Týden 7-8: 4 série × 12, maximální intenzita",
    ],
  },

  // ==================== CORE ====================
  {
    id: "core-beginner",
    bodyPartId: "core",
    name: "Stabilní střed - Start",
    description: "Posilování hlubokého stabilizačního systému. Základ pro všechny sporty.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["core-1", "core-2", "core-3"],
    rating: 4.6,
    ratingCount: 134,
    tags: ["Domácí", "Bez vybavení", "Stabilita"],
    estimatedMinutes: 15,
    weeklyProgression: [
      "Týden 1-2: Plank 20s, Dead Bug 2×8, Bird Dog 2×8",
      "Týden 3-4: Plank 30s, Dead Bug 3×10, Bird Dog 3×10",
      "Týden 5-6: Plank 45s, Dead Bug 3×12, Bird Dog 3×12",
    ],
  },
  {
    id: "core-advanced",
    bodyPartId: "core",
    name: "Neprůstřelný core",
    description: "Pokročilý program pro maximální stabilitu. Zahrnuje rotační a anti-rotační cviky.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 4,
    exercises: ["core-1", "core-4", "core-5", "core-6"],
    rating: 4.3,
    ratingCount: 67,
    tags: ["Pokročilý", "Kladka", "Rotace"],
    estimatedMinutes: 25,
    weeklyProgression: [
      "Týden 1-2: 2 série každý cvik, seznámení",
      "Týden 3-4: 3 série, zvýšení výdrží a opakování",
      "Týden 5-6: 3 série + boční plank variace",
      "Týden 7-8: 4 série, plná intenzita",
    ],
  },

  // ==================== ZÁDA (back) ====================
  {
    id: "back-beginner",
    bodyPartId: "back",
    name: "Rovná záda - Start",
    description: "Prevence bolestí zad a zlepšení držení těla. Bez vybavení.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["back-4", "back-5", "back-3"],
    rating: 4.7,
    ratingCount: 156,
    tags: ["Domácí", "Prevence", "Držení těla"],
    estimatedMinutes: 15,
    weeklyProgression: [
      "Týden 1-2: 2 série × 8 opakování, pomalé tempo",
      "Týden 3-4: 3 série × 10 opakování, výdrže 3s nahoře",
      "Týden 5-6: 3 série × 12 opakování, přidání kladky",
    ],
  },
  {
    id: "back-strength",
    bodyPartId: "back",
    name: "Široká záda",
    description: "Budování V-shape postavy. Shyby, přítahy a kladka.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 3,
    exercises: ["back-1", "back-2", "back-3"],
    rating: 4.5,
    ratingCount: 91,
    tags: ["Posilovna", "V-shape", "Síla"],
    estimatedMinutes: 35,
    weeklyProgression: [
      "Týden 1-2: 3 série, lehčí váhy / asistované shyby",
      "Týden 3-4: 3 série × 10, zvýšení váhy",
      "Týden 5-6: 4 série × 8, těžké váhy",
      "Týden 7-8: 4 série × 10, progresivní přetížení",
    ],
  },

  // ==================== NOHY (legs) ====================
  {
    id: "legs-beginner",
    bodyPartId: "legs",
    name: "Silné nohy - Základ",
    description: "Od nuly k prvním dřepům. Vlastní váha, postupný nárůst.",
    difficulty: "Začátečník",
    durationWeeks: 6,
    frequencyPerWeek: 3,
    exercises: ["legs-4", "legs-5", "legs-8"],
    rating: 4.5,
    ratingCount: 121,
    tags: ["Domácí", "Bez vybavení", "Začátečník"],
    estimatedMinutes: 20,
    weeklyProgression: [
      "Týden 1-2: 2 série × 10 opakování každý cvik",
      "Týden 3-4: 3 série × 12 opakování, přidat výdrže",
      "Týden 5-6: 3 série × 15 opakování, pomalejší tempo",
    ],
  },
  {
    id: "legs-power",
    bodyPartId: "legs",
    name: "Leg Day Beast",
    description: "Intenzivní leg day pro maximální sílu a objem. Dřepy, mrtvý tah, leg press.",
    difficulty: "Střední",
    durationWeeks: 8,
    frequencyPerWeek: 3,
    exercises: ["legs-1", "legs-2", "legs-3", "legs-6"],
    rating: 4.4,
    ratingCount: 78,
    tags: ["Posilovna", "Síla", "Objem"],
    estimatedMinutes: 40,
    weeklyProgression: [
      "Týden 1-2: 3 série × 10, technika a lehčí váhy",
      "Týden 3-4: 3 série × 12, zvýšení zátěže",
      "Týden 5-6: 4 série × 8, těžké váhy",
      "Týden 7-8: 4 série × 10, maxout týden",
    ],
  },
  {
    id: "legs-home",
    bodyPartId: "legs",
    name: "Nohy doma",
    description: "Efektivní trénink nohou jen s vlastní váhou. Hip thrusty, výpady, dřepy.",
    difficulty: "Začátečník",
    durationWeeks: 4,
    frequencyPerWeek: 4,
    exercises: ["legs-4", "legs-5", "legs-7", "legs-8"],
    rating: 4.3,
    ratingCount: 145,
    tags: ["Domácí", "Rychlý", "Hýždě"],
    estimatedMinutes: 15,
    weeklyProgression: [
      "Týden 1: 2 série × 10 každý cvik",
      "Týden 2: 2 série × 15 každý cvik",
      "Týden 3: 3 série × 12 každý cvik",
      "Týden 4: 3 série × 15 + výdrže",
    ],
  },
];

export function getPlansForBodyPart(bodyPartId: string): BodyPartPlan[] {
  return allPlans
    .filter((p) => p.bodyPartId === bodyPartId)
    .sort((a, b) => {
      const diffOrder = { "Začátečník": 0, "Střední": 1, "Pokročilý": 2 };
      return (diffOrder[a.difficulty] ?? 0) - (diffOrder[b.difficulty] ?? 0);
    });
}

export function getPlanById(planId: string): BodyPartPlan | undefined {
  return allPlans.find((p) => p.id === planId);
}
