import { MartialArt } from "@/types";

export const martialArtsData: MartialArt[] = [
  {
    id: "boxing",
    name: "Box",
    emoji: "🥊",
    description: "Klasické úderové umění. Nauč se jab, cross, hook a uppercut. Skvělé kardio a sebevědomí.",
    color: "#ef4444",
    difficulty: "Začátečník",
    benefits: ["Kardio kondice", "Koordinace", "Sebevědomí", "Reflexy", "Spalování tuků"],
    durationWeeks: 12,
    frequencyPerWeek: 3,
    techniques: [
      "Jab (přímý úder přední rukou)",
      "Cross (přímý úder zadní rukou)",
      "Hook (boční hák)",
      "Uppercut (spodní hák)",
      "Obranný kryt a úhyby",
      "Pohyb v ringu (footwork)",
      "Kombinace 1-2, 1-2-3",
      "Práce na pytli a lapách",
    ],
  },
  {
    id: "mma",
    name: "MMA",
    emoji: "🔥",
    description: "Smíšená bojová umění kombinující údery, kopy, zápas a submise. Kompletní bojovník.",
    color: "#f59e0b",
    difficulty: "Střední",
    benefits: ["Celkový fitness", "Sebevědomí", "Disciplína", "Síla", "Vytrvalost"],
    durationWeeks: 16,
    frequencyPerWeek: 4,
    techniques: [
      "Základní údery (jab, cross, hook)",
      "Základní kopy (low kick, middle kick)",
      "Takedowny (double leg, single leg)",
      "Ground & pound",
      "Základní submise (rear naked choke, armbar)",
      "Obrana na zemi (guard)",
      "Clinch práce",
      "Přechody mezi postoji",
    ],
  },
  {
    id: "karate",
    name: "Karate",
    emoji: "🥋",
    description: "Tradiční japonské bojové umění. Kata, kumite a kihon tvoří tři pilíře tréninku.",
    color: "#8b5cf6",
    difficulty: "Začátečník",
    benefits: ["Disciplína", "Flexibilita", "Koncentrace", "Sebevědomí", "Rovnováha"],
    durationWeeks: 12,
    frequencyPerWeek: 3,
    techniques: [
      "Kihon (základní techniky - údery, bloky)",
      "Oi-zuki (přímý úder vpřed)",
      "Gyaku-zuki (opačný úder)",
      "Mae-geri (přímý kop)",
      "Mawashi-geri (kruhový kop)",
      "Age-uke (horní blok)",
      "Kata (formální sestavy)",
      "Kumite (volný boj)",
    ],
  },
  {
    id: "bjj",
    name: "Jiu-Jitsu (BJJ)",
    emoji: "🤼",
    description: "Brazilské jiu-jitsu se zaměřuje na boj na zemi. Submise, sweepy a kontrola pozic.",
    color: "#3b82f6",
    difficulty: "Střední",
    benefits: ["Řešení problémů", "Flexibilita", "Core síla", "Trpělivost", "Sebevědomí"],
    durationWeeks: 16,
    frequencyPerWeek: 3,
    techniques: [
      "Closed guard (uzavřený guard)",
      "Open guard varianty",
      "Sweepy (přetočení soupeře)",
      "Mount a side control",
      "Armbar (páka na loket)",
      "Triangle choke (trojúhelníkové škrcení)",
      "Rear naked choke (škrcení zezadu)",
      "Shrimping a bridging (pohyb na zemi)",
    ],
  },
  {
    id: "kickbox",
    name: "Kickbox",
    emoji: "🦵",
    description: "Kombinace boxerských úderů a kopů. Dynamický a energický styl boje.",
    color: "#10b981",
    difficulty: "Začátečník",
    benefits: ["Kardio", "Síla nohou", "Koordinace", "Spalování kalorií", "Rychlost"],
    durationWeeks: 12,
    frequencyPerWeek: 3,
    techniques: [
      "Přímé údery (jab, cross)",
      "Háky a uppercut",
      "Front kick (přímý kop)",
      "Roundhouse kick (kruhový kop)",
      "Low kick",
      "Kombinace ruce + nohy",
      "Obranné techniky",
      "Práce na pytli a sparring",
    ],
  },
  {
    id: "muay-thai",
    name: "Muay Thai",
    emoji: "🇹🇭",
    description: "Thajský box využívá 8 zbraní těla - pěsti, lokty, kolena a holeně. Umění osmi končetin.",
    color: "#e53935",
    difficulty: "Střední",
    benefits: ["Síla celého těla", "Tvrdost", "Kardio", "Flexibilita kyčlí", "Mentální odolnost"],
    durationWeeks: 14,
    frequencyPerWeek: 4,
    techniques: [
      "Teep (přímý kop / push kick)",
      "Roundhouse kick (kruhový kop holeně)",
      "Lokty (horizontální, diagonální, spodní)",
      "Kolena (přímé, kruhové)",
      "Clinch (uchopení a práce zblízka)",
      "Long guard (prodloužený kryt)",
      "Kombinace všech 8 zbraní",
      "Wai kru (tradiční rituální tanec)",
    ],
  },
  {
    id: "judo",
    name: "Judo",
    emoji: "🏅",
    description: "Japonské umění hodů. Využij sílu soupeře proti němu. Cesta jemnosti.",
    color: "#06b6d4",
    difficulty: "Začátečník",
    benefits: ["Rovnováha", "Core síla", "Pádová technika", "Disciplína", "Celková koordinace"],
    durationWeeks: 12,
    frequencyPerWeek: 3,
    techniques: [
      "Ukemi (pádová technika)",
      "O-goshi (hod přes bok)",
      "Seoi-nage (hod přes rameno)",
      "Osoto-gari (velký vnější srp)",
      "Uchimata (vnitřní srp stehnem)",
      "Kesa-gatame (kontrola z boku)",
      "Ne-waza (boj na zemi)",
      "Randori (volný tréninkový boj)",
    ],
  },
  {
    id: "wrestling",
    name: "Zápas / Wrestling",
    emoji: "💪",
    description: "Jeden z nejstarších sportů. Takedowny, kontrola soupeře a ground work.",
    color: "#f97316",
    difficulty: "Střední",
    benefits: ["Výbušná síla", "Vytrvalost", "Mentální tvrdost", "Core síla", "Koordinace"],
    durationWeeks: 14,
    frequencyPerWeek: 4,
    techniques: [
      "Postoj a stance (bojový postoj)",
      "Double leg takedown",
      "Single leg takedown",
      "Sprawl (obrana proti takedownu)",
      "Fireman's carry (přehoz přes rameno)",
      "Kontrola na zemi (top position)",
      "Otáčení soupeře (turns)",
      "Chain wrestling (řetězení technik)",
    ],
  },
];

export function getMartialArtById(id: string): MartialArt | undefined {
  return martialArtsData.find((ma) => ma.id === id);
}
