import { SupplementInfo } from "@/types";

export const supplementsDatabase: SupplementInfo[] = [
  // ==================== PROTEINY ====================
  {
    id: "supp-protein-1",
    name: "Syrovátkový protein (Whey Concentrate)",
    category: "protein",
    description: "Nejpopulárnější forma proteinu ze syrovátky. Obsahuje 70-80% bílkovin, rychle se vstřebává.",
    benefits: ["Rychlá absorpce", "Podpora svalového růstu", "Bohatý aminokyselinový profil", "Dostupná cena"],
    dosage: "25-50g denně",
    timing: "Po tréninku nebo mezi jídly",
    sideEffects: ["Nadýmání u laktózově intolerantních", "Možné zažívací potíže při vysokých dávkách"],
    emoji: "🥛",
    rating: 5,
    evidence: "vysoká",
  },
  {
    id: "supp-protein-2",
    name: "Syrovátkový izolát (Whey Isolate)",
    category: "protein",
    description: "Čistější forma whey proteinu s 90%+ obsahem bílkovin. Minimální laktóza a tuky.",
    benefits: ["Vysoká čistota", "Minimální laktóza", "Rychlá absorpce", "Nízký obsah tuků"],
    dosage: "25-40g denně",
    timing: "Po tréninku",
    sideEffects: ["Vyšší cena", "Vzácně zažívací potíže"],
    emoji: "💪",
    rating: 5,
    evidence: "vysoká",
  },
  {
    id: "supp-protein-3",
    name: "Kasein (Casein Protein)",
    category: "protein",
    description: "Pomalu se vstřebávající mléčný protein. Zásobuje svaly aminokyselinami po dobu 6-8 hodin.",
    benefits: ["Pomalé uvolňování", "Anti-katabolický efekt", "Ideální před spaním", "Podpora regenerace"],
    dosage: "25-40g denně",
    timing: "Před spaním nebo mezi jídly",
    sideEffects: ["Pomalejší trávení", "Nadýmání u citlivých jedinců"],
    emoji: "🌙",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-protein-4",
    name: "Hovězí protein (Beef Protein)",
    category: "protein",
    description: "Protein z hydrolyzovaného hovězího masa. Alternativa pro alergiky na mléko.",
    benefits: ["Bez laktózy", "Vysoký obsah kolagenu", "Bohatý na železo", "Dobrá stravitelnost"],
    dosage: "25-40g denně",
    timing: "Po tréninku nebo mezi jídly",
    sideEffects: ["Specifická chuť", "Vyšší cena"],
    emoji: "🥩",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-protein-5",
    name: "Rostlinný protein (Plant Protein)",
    category: "protein",
    description: "Směs hrachového, rýžového a konopného proteinu. Vhodný pro vegany.",
    benefits: ["Vegan friendly", "Hypoalergenní", "Bohatý na vlákninu", "Udržitelný zdroj"],
    dosage: "30-50g denně",
    timing: "Po tréninku nebo mezi jídly",
    sideEffects: ["Nižší biologická hodnota", "Písčitá textura", "Specifická chuť"],
    emoji: "🌱",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-protein-6",
    name: "Vaječný protein (Egg Protein)",
    category: "protein",
    description: "Protein z vaječných bílků. Střední rychlost absorpce, kompletní aminokyselinový profil.",
    benefits: ["Kompletní aminokyseliny", "Bez laktózy", "Střední absorpce", "Vysoká biologická hodnota"],
    dosage: "25-40g denně",
    timing: "Kdykoli během dne",
    sideEffects: ["Vyšší cena", "Možná alergie na vejce"],
    emoji: "🥚",
    rating: 4,
    evidence: "vysoká",
  },

  // ==================== AMINOKYSELINY ====================
  {
    id: "supp-amino-1",
    name: "BCAA (Rozvětvené aminokyseliny)",
    category: "amino",
    description: "Leucin, isoleucin a valin v poměru 2:1:1. Klíčové pro svalovou proteosyntézu.",
    benefits: ["Podpora svalového růstu", "Snížení únavy", "Ochrana svalů při redukci", "Rychlá regenerace"],
    dosage: "5-10g denně",
    timing: "Během tréninku nebo po něm",
    sideEffects: ["Zbytečné při dostatečném příjmu proteinu", "Možná nevolnost nalačno"],
    emoji: "⚡",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-amino-2",
    name: "EAA (Esenciální aminokyseliny)",
    category: "amino",
    description: "Všech 9 esenciálních aminokyselin, které tělo nedokáže vyrobit samo. Nadřazené BCAA.",
    benefits: ["Kompletní aminokyselinový profil", "Lepší svalová syntéza než BCAA", "Podpora regenerace"],
    dosage: "10-15g denně",
    timing: "Během tréninku",
    sideEffects: ["Hořká chuť", "Vyšší cena než BCAA"],
    emoji: "🧬",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-amino-3",
    name: "L-Glutamin",
    category: "amino",
    description: "Nejhojnější aminokyselina v těle. Podpora imunity a střevní bariéry.",
    benefits: ["Podpora imunity", "Zdraví střev", "Regenerace po intenzivním tréninku"],
    dosage: "5-10g denně",
    timing: "Po tréninku nebo před spaním",
    sideEffects: ["Většinou dobře tolerován", "Zbytečný při běžné zátěži"],
    emoji: "🛡️",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-amino-4",
    name: "L-Karnitin",
    category: "amino",
    description: "Transportuje mastné kyseliny do mitochondrií k oxidaci. Podpora metabolismu tuků.",
    benefits: ["Podpora spalování tuků", "Lepší regenerace", "Ochrana srdce", "Zvýšení energie"],
    dosage: "1-3g denně",
    timing: "Před tréninkem s jídlem",
    sideEffects: ["Rybí pach potu při vysokých dávkách", "Nevolnost"],
    emoji: "🔥",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-amino-5",
    name: "Beta-Alanin",
    category: "amino",
    description: "Zvyšuje hladinu karnosinu ve svalech, čímž zpomaluje únavu při intenzivním cvičení.",
    benefits: ["Oddálení únavy", "Lepší výkon při vysoké intenzitě", "Zvýšení svalové vytrvalosti"],
    dosage: "3-6g denně (rozdělit do menších dávek)",
    timing: "Kdykoliv, pravidelně každý den",
    sideEffects: ["Mravenčení kůže (parestezie)", "Neškodné, přechodné"],
    emoji: "⏱️",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-amino-6",
    name: "Citrullin malát",
    category: "amino",
    description: "Zvyšuje produkci oxidu dusnatého, zlepšuje průtok krve a svalovou pumpu.",
    benefits: ["Lepší svalová pumpa", "Zvýšení vytrvalosti", "Snížení bolestivosti svalů", "Podpora NO produkce"],
    dosage: "6-8g denně",
    timing: "30-60 minut před tréninkem",
    sideEffects: ["Vzácně zažívací potíže", "Obecně velmi bezpečný"],
    emoji: "💨",
    rating: 4,
    evidence: "vysoká",
  },

  // ==================== VITAMÍNY ====================
  {
    id: "supp-vitamin-1",
    name: "Vitamín D3",
    category: "vitamin",
    description: "Sluneční vitamín. Většina populace má nedostatek, zejména v zimních měsících.",
    benefits: ["Podpora kostí", "Posílení imunity", "Podpora testosteronu", "Zlepšení nálady"],
    dosage: "2000-5000 IU denně",
    timing: "S tučným jídlem pro lepší vstřebávání",
    sideEffects: ["Toxicita při extrémně vysokých dávkách", "Hyperkalcémie"],
    emoji: "☀️",
    rating: 5,
    evidence: "vysoká",
  },
  {
    id: "supp-vitamin-2",
    name: "Vitamín C",
    category: "vitamin",
    description: "Silný antioxidant, podpora imunity a tvorby kolagenu. Esenciální pro sportovce.",
    benefits: ["Posílení imunity", "Antioxidační ochrana", "Podpora tvorby kolagenu", "Lepší vstřebávání železa"],
    dosage: "500-1000mg denně",
    timing: "S jídlem, rozdělit do 2 dávek",
    sideEffects: ["Zažívací potíže při vysokých dávkách", "Průjem"],
    emoji: "🍊",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-vitamin-3",
    name: "Vitamín B komplex",
    category: "vitamin",
    description: "Skupina 8 vitamínů B důležitých pro energetický metabolismus a nervový systém.",
    benefits: ["Energetický metabolismus", "Podpora nervového systému", "Tvorba červených krvinek", "Snížení únavy"],
    dosage: "Dle doporučení na obale",
    timing: "Ráno s jídlem",
    sideEffects: ["Žlutá moč (neškodné)", "Nevolnost nalačno"],
    emoji: "⚡",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-vitamin-4",
    name: "Zinek",
    category: "vitamin",
    description: "Esenciální minerál pro imunitu, hojení ran a produkci testosteronu.",
    benefits: ["Podpora imunity", "Podpora testosteronu", "Hojení ran", "Zdravá kůže"],
    dosage: "15-30mg denně",
    timing: "S jídlem (ne s mléčnými výrobky)",
    sideEffects: ["Nevolnost nalačno", "Interference s absorpcí mědi při vysokých dávkách"],
    emoji: "🔩",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-vitamin-5",
    name: "Hořčík (Magnesium)",
    category: "vitamin",
    description: "Důležitý minerál pro svalovou funkci, spánek a regeneraci. Deficit je velmi častý.",
    benefits: ["Svalová relaxace", "Lepší spánek", "Snížení křečí", "Podpora nervového systému"],
    dosage: "200-400mg denně (elementárního Mg)",
    timing: "Večer před spaním",
    sideEffects: ["Průjem při vysokých dávkách", "Některé formy se hůře vstřebávají"],
    emoji: "💤",
    rating: 5,
    evidence: "vysoká",
  },
  {
    id: "supp-vitamin-6",
    name: "Omega-3 (Rybí olej)",
    category: "vitamin",
    description: "EPA a DHA mastné kyseliny. Protizánětlivé účinky, podpora srdce a mozku.",
    benefits: ["Protizánětlivé účinky", "Zdraví srdce", "Podpora mozku", "Lepší regenerace"],
    dosage: "2-3g EPA+DHA denně",
    timing: "S tučným jídlem",
    sideEffects: ["Rybí říhání", "Řidší krev při vysokých dávkách"],
    emoji: "🐟",
    rating: 5,
    evidence: "vysoká",
  },

  // ==================== MINERÁLY ====================
  {
    id: "supp-mineral-1",
    name: "Vápník (Calcium)",
    category: "mineral",
    description: "Nejhojnější minerál v těle. Klíčový pro kosti, zuby a svalovou kontrakci.",
    benefits: ["Pevné kosti a zuby", "Svalová kontrakce", "Nervové přenosy", "Srážení krve"],
    dosage: "500-1000mg denně",
    timing: "Rozdělit do 2 dávek s jídlem",
    sideEffects: ["Zácpa", "Interference s absorpcí železa a zinku"],
    emoji: "🦴",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-mineral-2",
    name: "Železo (Iron)",
    category: "mineral",
    description: "Esenciální pro transport kyslíku v krvi. Deficit je častý zejména u žen a vytrvalostních sportovců.",
    benefits: ["Transport kyslíku", "Prevence anémie", "Energetický metabolismus", "Imunitní funkce"],
    dosage: "14-18mg denně (dle pohlaví)",
    timing: "Nalačno s vitamínem C pro lepší vstřebávání",
    sideEffects: ["Zácpa", "Nevolnost", "Tmavá stolice", "Toxicita při předávkování"],
    emoji: "🩸",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-mineral-3",
    name: "Draslík (Potassium)",
    category: "mineral",
    description: "Elektrolyt důležitý pro svalovou funkci, srdeční rytmus a rovnováhu tekutin.",
    benefits: ["Svalová funkce", "Regulace krevního tlaku", "Rovnováha tekutin", "Nervové přenosy"],
    dosage: "200-400mg jako doplněk (většinu získat z potravy)",
    timing: "S jídlem",
    sideEffects: ["Nebezpečný při předávkování", "Zažívací potíže"],
    emoji: "🍌",
    rating: 3,
    evidence: "vysoká",
  },
  {
    id: "supp-mineral-4",
    name: "Multivitamín",
    category: "mineral",
    description: "Pojistka proti mikro-nutričním deficitům. Obsahuje směs vitamínů a minerálů.",
    benefits: ["Prevence deficitů", "Celková zdravotní podpora", "Pohodlné doplnění", "Podpora imunity"],
    dosage: "1 tableta denně dle produktu",
    timing: "S jídlem ráno",
    sideEffects: ["Nevolnost nalačno", "Předávkování jednotlivými vitamíny při kombinaci s dalšími suplementy"],
    emoji: "💊",
    rating: 3,
    evidence: "střední",
  },

  // ==================== VÝKON (PERFORMANCE) ====================
  {
    id: "supp-perf-1",
    name: "Kreatin monohydrát",
    category: "performance",
    description: "Nejprostudovanější a nejúčinnější suplement na světě. Zvyšuje sílu, výkon a objem svalů.",
    benefits: ["Zvýšení síly o 5-10%", "Větší svalový objem", "Lepší regenerace", "Kognitivní benefity"],
    dosage: "3-5g denně (bez nutnosti loading fáze)",
    timing: "Kdykoliv denně, konzistentně",
    sideEffects: ["Zadržování vody (1-2 kg)", "Vzácně zažívací potíže"],
    emoji: "🏆",
    rating: 5,
    evidence: "vysoká",
  },
  {
    id: "supp-perf-2",
    name: "Kofein",
    category: "performance",
    description: "Nejpoužívanější stimulant na světě. Zvyšuje bdělost, sílu a vytrvalost.",
    benefits: ["Zvýšení energie", "Lepší fokus", "Zvýšení síly", "Spalování tuků"],
    dosage: "100-400mg denně",
    timing: "30-60 minut před tréninkem",
    sideEffects: ["Nespavost", "Úzkost", "Zvýšený tep", "Tolerance a závislost"],
    emoji: "☕",
    rating: 5,
    evidence: "vysoká",
  },
  {
    id: "supp-perf-3",
    name: "Pre-workout (přípravek před tréninkem)",
    category: "performance",
    description: "Směs stimulantů a výkonnostních látek. Obvykle obsahuje kofein, beta-alanin, citrullin.",
    benefits: ["Okamžitý nárůst energie", "Lepší pumpa", "Zvýšený fokus", "Oddálení únavy"],
    dosage: "1 odměrka dle produktu",
    timing: "20-30 minut před tréninkem",
    sideEffects: ["Nespavost při pozdním užití", "Mravenčení", "Zvýšený tep", "Crash po odeznění"],
    emoji: "🚀",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-perf-4",
    name: "Ashwagandha (KSM-66)",
    category: "performance",
    description: "Adaptogenní bylina. Snižuje kortizol, podporuje testosteron a zlepšuje regeneraci.",
    benefits: ["Snížení stresu a kortizolu", "Podpora testosteronu", "Lepší spánek", "Zvýšení síly"],
    dosage: "300-600mg denně (KSM-66 extrakt)",
    timing: "Večer před spaním",
    sideEffects: ["Ospalost", "Zažívací potíže", "Interakce s léky na štítnou žlázu"],
    emoji: "🌿",
    rating: 4,
    evidence: "střední",
  },
  {
    id: "supp-perf-5",
    name: "HMB (Beta-hydroxy beta-methylbutyrát)",
    category: "performance",
    description: "Metabolit leucinu. Brání odbourávání svalů, nejvíce efektivní u začátečníků.",
    benefits: ["Anti-katabolický efekt", "Podpora regenerace", "Ochrana svalů při redukci"],
    dosage: "3g denně rozdělit do 3 dávek",
    timing: "S jídly během dne",
    sideEffects: ["Minimální vedlejší účinky", "Vyšší cena"],
    emoji: "🛡️",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-perf-6",
    name: "Taurin",
    category: "performance",
    description: "Aminokyselina s antioxidačními vlastnostmi. Podporuje svalovou funkci a hydrataci buněk.",
    benefits: ["Antioxidační ochrana", "Podpora svalové funkce", "Lepší hydratace buněk", "Podpora srdce"],
    dosage: "1-3g denně",
    timing: "Před tréninkem nebo s jídlem",
    sideEffects: ["Velmi bezpečný", "Vzácně mírné zažívací potíže"],
    emoji: "💧",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-perf-7",
    name: "Elektrolyty",
    category: "performance",
    description: "Směs sodíku, draslíku, hořčíku a vápníku. Klíčové pro hydrataci a svalovou funkci.",
    benefits: ["Prevence křečí", "Optimální hydratace", "Lepší výkon", "Rovnováha minerálů"],
    dosage: "Dle potřeby během/po tréninku",
    timing: "Během intenzivního tréninku nebo v horku",
    sideEffects: ["Nadměrný příjem sodíku", "Zažívací potíže při vysoké koncentraci"],
    emoji: "⚡",
    rating: 4,
    evidence: "vysoká",
  },

  // ==================== ZDRAVÍ (HEALTH) ====================
  {
    id: "supp-health-1",
    name: "Probiotika",
    category: "health",
    description: "Živé prospěšné bakterie pro zdraví střevního mikrobiomu. Základ celkového zdraví.",
    benefits: ["Zdraví střev", "Posílení imunity", "Lepší trávení", "Produkce vitamínů"],
    dosage: "10-50 miliard CFU denně",
    timing: "S jídlem nebo nalačno (dle kmene)",
    sideEffects: ["Přechodné nadýmání", "Plynatost v prvních dnech"],
    emoji: "🦠",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-health-2",
    name: "Kurkumin (Turmeric)",
    category: "health",
    description: "Aktivní složka kurkumy. Silné protizánětlivé a antioxidační účinky.",
    benefits: ["Protizánětlivé účinky", "Antioxidační ochrana", "Podpora kloubů", "Lepší regenerace"],
    dosage: "500-1000mg denně (s piperinem pro lepší vstřebávání)",
    timing: "S tučným jídlem",
    sideEffects: ["Zažívací potíže", "Může ztenčovat krev"],
    emoji: "🟡",
    rating: 4,
    evidence: "střední",
  },
  {
    id: "supp-health-3",
    name: "Kolagen",
    category: "health",
    description: "Strukturální protein pro kůži, klouby, šlachy a kosti. Produkce klesá s věkem.",
    benefits: ["Zdraví kloubů", "Elasticita kůže", "Pevnost šlach", "Podpora kostí"],
    dosage: "10-15g denně",
    timing: "Ráno nalačno nebo s vitamínem C",
    sideEffects: ["Většinou velmi dobře tolerován", "Specifická chuť"],
    emoji: "✨",
    rating: 4,
    evidence: "střední",
  },
  {
    id: "supp-health-4",
    name: "Melatonin",
    category: "health",
    description: "Hormon spánku. Pomáhá regulovat cirkadiánní rytmus a zlepšit kvalitu spánku.",
    benefits: ["Rychlejší usínání", "Regulace spánkového cyklu", "Antioxidační účinky", "Podpora regenerace"],
    dosage: "0.5-3mg denně",
    timing: "30-60 minut před spaním",
    sideEffects: ["Ospalost ráno", "Živé sny", "Tolerance při dlouhodobém užívání"],
    emoji: "😴",
    rating: 4,
    evidence: "vysoká",
  },
  {
    id: "supp-health-5",
    name: "Adaptogeny (Rhodiola, Ženšen)",
    category: "health",
    description: "Bylinné přípravky pomáhající tělu zvládat stres. Rhodiola a ženšen jsou nejprostudovanější.",
    benefits: ["Snížení stresu", "Zvýšení energie", "Lepší kognitivní funkce", "Podpora imunity"],
    dosage: "Rhodiola 200-600mg, Ženšen 200-400mg denně",
    timing: "Ráno s jídlem",
    sideEffects: ["Nespavost při pozdním užití", "Interakce s léky"],
    emoji: "🌿",
    rating: 3,
    evidence: "střední",
  },

  // ==================== FAT BURNERY ====================
  {
    id: "supp-fat-1",
    name: "CLA (Konjugovaná kyselina linolová)",
    category: "fat_burner",
    description: "Mastná kyselina s mírným účinkem na tělesnou kompozici. Snižuje ukládání tuků.",
    benefits: ["Mírná podpora spalování tuků", "Zachování svalové hmoty", "Snížení ukládání tuků"],
    dosage: "3-6g denně",
    timing: "S hlavními jídly",
    sideEffects: ["Zažívací potíže", "Mírný efekt", "Dlouhodobé užívání potřeba"],
    emoji: "🔥",
    rating: 2,
    evidence: "nízká",
  },
  {
    id: "supp-fat-2",
    name: "Zelený čaj extrakt (EGCG)",
    category: "fat_burner",
    description: "Katechiny ze zeleného čaje zvyšují metabolismus a oxidaci tuků.",
    benefits: ["Zvýšení metabolismu", "Antioxidační ochrana", "Mírná podpora spalování", "Zdraví srdce"],
    dosage: "250-500mg EGCG denně",
    timing: "S jídlem (ne nalačno)",
    sideEffects: ["Poškození jater při vysokých dávkách nalačno", "Nevolnost", "Nespavost (obsahuje kofein)"],
    emoji: "🍵",
    rating: 3,
    evidence: "střední",
  },
  {
    id: "supp-fat-3",
    name: "Synefrin (Bitter Orange)",
    category: "fat_burner",
    description: "Přírodní stimulant z hořkého pomeranče. Mírně zvyšuje metabolismus a termogenezi.",
    benefits: ["Zvýšení metabolismu", "Termogenní efekt", "Potlačení chuti k jídlu"],
    dosage: "10-20mg 2-3x denně",
    timing: "Před jídly",
    sideEffects: ["Zvýšený krevní tlak", "Zrychlený tep", "Nespavost", "Nekombinovat s kofeinem v nadměrném množství"],
    emoji: "🍊",
    rating: 2,
    evidence: "nízká",
  },
  {
    id: "supp-fat-4",
    name: "Yohimbin",
    category: "fat_burner",
    description: "Alkaloid z kůry stromu Yohimbe. Blokuje alfa-2 receptory a podporuje spalování odolného tuku.",
    benefits: ["Spalování odolného tuku", "Zvýšení energie", "Podpora při redukci"],
    dosage: "2.5-20mg denně (postupně zvyšovat)",
    timing: "Nalačno před tréninkem",
    sideEffects: ["Úzkost", "Zvýšený krevní tlak", "Nevolnost", "Nespavost", "Potenciálně nebezpečný"],
    emoji: "⚠️",
    rating: 3,
    evidence: "střední",
  },
];

// Helper funkce
export function getSupplementsByCategory(category: SupplementInfo['category']): SupplementInfo[] {
  return supplementsDatabase.filter(s => s.category === category);
}

export function getSupplementById(id: string): SupplementInfo | undefined {
  return supplementsDatabase.find(s => s.id === id);
}

export function getTopRatedSupplements(limit = 10): SupplementInfo[] {
  return [...supplementsDatabase].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getHighEvidenceSupplements(): SupplementInfo[] {
  return supplementsDatabase.filter(s => s.evidence === 'vysoká');
}

export const supplementCategories = [
  { id: 'protein', name: 'Proteiny', emoji: '🥛' },
  { id: 'amino', name: 'Aminokyseliny', emoji: '🧬' },
  { id: 'vitamin', name: 'Vitamíny a minerály', emoji: '💊' },
  { id: 'mineral', name: 'Minerály', emoji: '🦴' },
  { id: 'performance', name: 'Výkon', emoji: '🚀' },
  { id: 'health', name: 'Zdraví', emoji: '🌿' },
  { id: 'fat_burner', name: 'Fat burnery', emoji: '🔥' },
] as const;
